### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by der-On** [Excodus/oc-translate-extended#10]
#6 was fixed in an already merged PR and is critical for multi-language sites including frontend user sessions. Please bump up the version containing this fix.

**Comment by rsobon** [comment]
I already pulled the changes from github to the octobercms plugin repository. It appears that if I don't increase version in the version.yaml file, existing installation won't know that they need to update. Fixed that now

**Comment by der-On** [comment]
Thanks allot!
