### ISSUE TITLE
Not saving in session

### ISSUE THREAD

**Issue by mariavilaro** [Excodus/oc-translate-extended#17]
My browser preferred language is "es", I change the language to "en" using the locale picker or loading a "en" url manyally, and then go to the home page / and it loads again the "es" locale. If I write a `dd($localeSession);` in routes.php on line 25, the value is always false, so I suppose the session is not started yet? Any clues?

**Comment by aurelien-roy** [comment]
Same issue here.
It seems indeed that session is not available yet. It is started with the StartSession middleware however middlewares are not started yet in App::before.
